### PR TITLE
Update to match neurodatascience/nipoppy:main

### PR DESCRIPTION
**Pull request by michellewang**
PR created/updated automatically by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action. Will be merged automatically by [automerge-action](https://github.com/pascalgn/automerge-action) if there are no merge conflicts.

### CODE REVIEW

**Review by bcmcpher — APPROVED** [review]
PR approved by [auto-approve-action](https://github.com/michellewang/auto-approve-action) GitHub action.

**Comment by michellewang** [comment]
@nikhil153 this is failing because of a conflict with an existing [README file](https://github.com/neurodatascience/nipoppy-nimhans_retro/blob/main/README.md) -- do you want to keep/rename that file (doesn't seem really specific to the dataset) or can we delete it?

**Comment by nikhil153** [comment]
It's definitely outdated. We can delete it.

**Comment by michellewang** [comment]
Deleted the old README, merging now

**Comment by michellewang** [comment]
Hm I guess something went not quite right -- now there is no README at all... Will try to fix it

**Comment by michellewang** [comment]
Ok so for some reason Git thinks `main` and `main-upstream` are not different event though one doesn't have a README and the other one does... Hopefully this is not super critical because I'm not sure how to fix it except by updating the README in the `nipoppy` repo to try to trigger this again.

**Pull request merged**
